version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "Building complete"
  test-production:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "Testing complete"
  deploy:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "Deploy complete"

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test-production:
          requires:
            - build
      - deploy:
          requires:
            - test-production
          filters:
            branches:
<<<<<<< HEAD
              only: Production #Should run on new branch.
=======
              only: Production #Should run on new branch.
>>>>>>> 888dc356355e86dc7ee3e49c6d67281a08baca5c
